name: wavetable_x
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  
dependencies:
  - python=3.6
  - pip
  - librosa==0.9.0
  - crepe==0.0.12
  - einops=0.3.0
  - tqdm=4.46.0
  - flask=1.1.2
  - pyyaml=5.3.1
  - ipykernel
  - h5py=2.7.0
  - pip:
      - tensorflow-gpu==2.3.0
      - effortless_config==0.7.0
      - SoundFile==0.10.3.post1
      - nnaudio==0.3.2
      - torch-tb-profiler==0.4.0
      - pillow==6.2.2 
      - matplotlib==3.1.3
      # pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html